(part "744770122"
    (packageRef "INDPM120120X800N")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "33")
    (property "Mouser2_Part_Number" "")
    (property "Mouser2_Price/Stock" "")
    (property "Manufacturer_Name" "Wurth Elektronik")
    (property "Manufacturer_Part_Number" "744770122")
    (property "Description" "WURTH ELEKTRONIK - 744770122 - Power Inductor (SMD), 22 H, 4.1 A, Shielded, 5 A, WE-PD Series, 12mm x 12mm x 8mm")
    (property "Datasheet_Link" "https://datasheet.datasheetarchive.com/originals/distributors/Datasheets_SAMA/5df985c0799d1d1baf5ad0b49bccb74f.pdf")
    (property "symbolName1" "744770122")
)
